---

- name: Install Nginx web server
  become: true
  apt:
    name: nginx
    state: latest
  notify: Restart Nginx

- name: Check Nginx default from available
  stat:
    path: /etc/nginx/sites-available/default
  register: nginx_avliable_stat

- name: Remove Nginx default from available
  when: nginx_avliable_stat.stat.exists
  become: true
  command: rm /etc/nginx/sites-available/default
  notify: Restart Nginx

- name: Check Nginx is enalbled default-site
  stat:
    path: /etc/nginx/sites-enabled/default
  register: nginx_enabled_stat

- name: Remove Nginx enalbled default-site
  when: nginx_enabled_stat.stat.exists
  become: true
  command: rm /etc/nginx/sites-enabled/default
  notify: Restart Nginx

- name: Add Symfony config template to the Nginx available sites
  become: true
  template:
    src: templates/symfony.conf
    dest: "/etc/nginx/sites-available/{{ server_name }}.conf"
  notify: Restart Nginx

- name: Enable Symfony config template from Nginx available sites
  become: true
  file:
    src: "/etc/nginx/sites-available/{{ server_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ server_name }}.conf"
    state: link
  notify: Restart Nginx

- name: Add enabled Nginx site to /etc/hosts
  become: true
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ server_name }}"
    line: "127.0.0.1 {{ server_name }}"
  notify: Restart Nginx
